[package]
name = "rremix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"

[dev-dependencies]
insta = "1.13.0"
test-case = "2.0.0"
